### ISSUE TITLE
Does the Hosted VSTS support building the linux container ?

### ISSUE THREAD

**Issue by RamprasathSaminathan** [Microsoft/vsts-image-generation#101]
Does Hosted VS2017 agent support in running building the linux container ?

**Comment by shaselsc** [comment]
I would like to know this as well.

**Comment by lokesh755** [comment]
I don't think you can build Linux containers on Hosted VS2017 agent. It has Windows 2016 server.

**Comment by bryanmacfarlane** [comment]
Note that we are considering creating some hosted "Windows Docker" and "Linux Docker" pools that just have docker and a list of documented images pre cached on them.   In our yaml support we're also about to preview build phase in container xxx and produce container yyy ( with producing popping out back to the host with sources and output available).

We're still working through our formal container support.

If you have a specific scenario you're interested in, you can specify it or email me.  That's bryanmac and it's at microsoft dot com.  Happy to ensure we're producing a roadmap that works for you.
