### ISSUE TITLE
Request: Update DotNetCore Runtime to 2.0.6

### ISSUE THREAD

**Issue by Hechamon** [Microsoft/vsts-image-generation#103]
Due to security concerns with asp.net 2.0.5 we upgraded our asp.net core server to 2.0.6, however now we cannot run our tests on Vsts hosted 2017 agents.

We would greatly appreciate an upgrade so we can get our CI pipelines running again.

See https://github.com/dotnet/announcements/issues/62 for details on the vulnerability.

**Comment by lokesh755** [comment]
We'll update the hosted agents probably with in a week.

**Comment by pasn** [comment]
Any update on this one?

**Comment by lokesh755** [comment]
Hosted agents update is already in progress. Will be done in next two days.

**Comment by lokesh755** [comment]
Hosted VS2017 agents are updated with Dotnet Runtime 2.0.6
