### ISSUE TITLE
Build agent failed to install msi

### ISSUE THREAD

**Issue by MengYunfan** [Microsoft/vsts-image-generation#104]
Error message.
> The Temp folder is on a drive that is full or is inaccessible. Free up space on the drive or verify that you have write permission on the Temp folder.

I can not use the nuget version of MicrosoftStoreServicesSDK, so i install MicrosoftStoreServicesSDK.msi in my local machine, but on vsts build agent  MicrosoftStoreServicesSDK installation was failed.

😂😂😂😂😂

This is msi version of [MicrosoftStoreServicesSDK](https://marketplace.visualstudio.com/items?itemName=AdMediator.MicrosoftStoreServicesSDK) .

and this is my install script's content.
```ps
# install MicrsoftStoreServicesSDK
cd $PSScriptRoot

msiexec /i MicrosoftStoreServicesSDK.msi /quiet
```

**Comment by chrisrpatterson** [comment]
Which pool are you targeting with your build.  The Hosted pool does not run as an admin account so you will not be able to install that package.  The Hosted VS 2017 pool does so you should be able to.

**Comment by MengYunfan** [comment]
@chrisrpatterson My build pool is Hosted VS 2017, but i can't install msi😂😂😂

**Comment by lokesh755** [comment]
I'm not sure why you're facing problem installing MSI, you should be able to run as Admin on Hosted VS2017.  Can you try installing VSIX plugin instead of MSI. You can follow similar pattern as installing WIX plugin. https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Vs2017/Install-Wix.ps1

**Comment by syedhassaanahmed** [comment]
I'm trying to install MSI from PS on Hosted agent 1803 (Can't use VS2017 in my case). Getting error
`This installation package could not be opened verify that the package exists and that you can access`
