### ISSUE TITLE
Hosted Agent Fails to Build new csproj format.

### ISSUE THREAD

**Issue by groogiam** [Microsoft/vsts-image-generation#121]
The hosted build agent fails when it attempts to build the new csproj. These projects build without a problem when running the agent locally. The error below is generated for all projects using the new csproj format. The Visual Studio build task is set to use the latest version of visual studio. Visual studio does not include this namespace in any of its project templates for .NET Standard.

It appears this image is defaulting to msbuild 14 rather than 14 even though the task has use the latest version of visual studio specified.

```
Error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
```

**Comment by chrisrpatterson** [comment]
For building .NET Standard targeted solutions you should use the Hosted VS 2017 pool
