### ISSUE TITLE
MacOS Preview Agent Node Version is Very Old

### ISSUE THREAD

**Issue by tylermurry** [Microsoft/vsts-image-generation#122]
I'm executing a build on a macOS Preview agent but the node/npm version is _very_ old:

`user-agent = "npm/3.10.10 node/v6.14.1 darwin x64"`

I believe the node version was [updated back in December](https://github.com/Microsoft/vsts-image-generation/pull/14) but this did not make it to macOS. Is the image managed by a different repo?

@phillipleblanc et all, what's the best way to get the macOS agent up to date?

**Comment by phillipleblanc** [comment]
@tylermurry Can you see if using the Node Tool Installer in your build works for you? https://docs.microsoft.com/en-us/vsts/build-release/tasks/tool/node-js?view=vsts
