### ISSUE TITLE
Intermittent sysprep issues when building the VS2017 image

### ISSUE THREAD

**Issue by NateB2** [Microsoft/vsts-image-generation#127]
When building the Windows Server 2016 VS2017 image, I've been running into intermittent sysprep issues where the image appears to have been created successfully, but when the image is used for a VM, the VM does not start successfully.  This has happened both with VHD images and with managed images (I'm using the VM size "Standard_F8s_v2" to build the images).   I looked at Microsoft's documentation for packer images, changed the sysprep step as per their recommendations, and it's been working fine since.  I created PR https://github.com/Microsoft/vsts-image-generation/pull/126 for this issue.

**Comment by chrisrpatterson** [comment]
PR #126 merged
