### ISSUE TITLE
VS2017 machine fails at VSTS agent installation

### ISSUE THREAD

**Issue by tomvo12** [Microsoft/vsts-image-generation#130]
Hi,

if you would like to use the VS2017 machine image as a base for a VSTS build agent you have to install the VSTS agent in the created machine. However, when you execute the MSI install, an error 1603 shows up. I have raised a support ticket with Microsoft and the result was that the folder "C:\Windows\Installer" is missing in the image. As soon as you create this folder, the MSI installer works and you can register the agent successfully.

So can you please make sure that this folder exists when the VHD image is created?

This could be reproduced with release/1804 (and 1803 as well).

Currently, the workaround is to have a custom installer script which creates the missing folder before installing the agent.

Thanks in advance,
Tom

**Comment by bryanmacfarlane** [comment]
Our agent does not have an MSI install.  It's a xcopy zip download

Can you clarify which msi you are referring to?

**Comment by tomvo12** [comment]
Hi Bryan, sorry. I was next to the track. The VSTS agent can be installed without a problem.
However, we monitor our private agents with OMS and the OMS agent is indeed an MSI package which fails to install using the OMS extension from Azure compute.
A manual installation of the OMS agent also fails. Microsoft Premier support found out that the folder was missing which leads to the error.

Sorry for the confusion :-).

Kind regards,
Tom

**Comment by lokesh755** [comment]
Hi Tom,

           To conserve space, we're removing the directories which are used while installation of software. "C:/Windows/Installer" is one of them (https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Finalize-VM.ps1#L18-L25 ) . I've added a fix to create empty directory.

**Comment by tomvo12** [comment]
Hi Lokesh!

Thanks a lot!
