### ISSUE TITLE
What is the timeframe for putting Windows SDK (1803) 17134

### ISSUE THREAD

**Issue by bibble235** [Microsoft/vsts-image-generation#134]
Thanks

**Comment by bryanmacfarlane** [comment]
What SDK are you referring to?

**Comment by bibble235** [comment]
Thanks for getting back, Windows

![image](https://user-images.githubusercontent.com/745357/40023226-78b68202-581e-11e8-9027-24f4ad869cf6.png)

**Comment by bryanmacfarlane** [comment]
Cool.  What pool are you using?  Hosted or Hosted VS 2017?

**Comment by bibble235** [comment]
It goes into Hosted VS 2017 queue

**Comment by onovotny** [comment]
This does not need to wait for VS 15.7, it has a separate installer.
https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk

More generally, as Windows 10 SDK's are safe for SxS install, we need the Windows 10 Insider SDK's installed on the hosted agents so projects can build bits using those SDK's and Windows can get feedback on them.

**Comment by bryanmacfarlane** [comment]
@onovotny - yep, the request if for the VS 2017 *image*

**Comment by bryanmacfarlane** [comment]
Our current answer is private agents (on azure VMS - you can even fork our image gen).  On the horizon we have bring your own subscription and other pool options where you can control the vm specs, networking and image but we automate managing it.

**Comment by onovotny** [comment]
@bryanmacfarlane private agents can never be secure for public PR's. This impacts any OSS project that's targeting Windows, including the Windows Community Toolkit. We need those insider SDK's sooner than that, especially since they're SxS. It won't break anything.

**Comment by bryanmacfarlane** [comment]
we have 'single use' options with different pools under development.  not ready to detail.   the current model for hosted images is release only products even if the promise of when released is SxS.  Regarding 1803 specifically, we're looking at creating a new pool with a new preview image since that's critical for our docker scenarios.

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-image-generation/issues/144

**Comment by lokesh755** [comment]
Hosted agents are update to VS 15.7.2 which includes Windows SDK 17134
