### ISSUE TITLE
New image is not using LTS version of Node

### ISSUE THREAD

**Issue by luuksommers** [Microsoft/vsts-image-generation#135]
Node 10.0.0 is not yet in the LTS support see (https://github.com/nodejs/Release). 

Why is it now in the hosted build agent? Our build breaks using node 10, now we need to update all developer machines.

**Comment by bryanmacfarlane** [comment]
Which image are you referring to?  Vs2017 hosted image calls choco install nodejs-lts

https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Install-NodeLts.ps1#L16 

That should install 8.x

**Comment by bryanmacfarlane** [comment]
We found the issue - typescript choco install is overwriting node version.  @lokesh755 is preparing a fix

**Comment by bryanmacfarlane** [comment]
workaround is to use the node tool installer task with 8.x (it will prepend the path)

**Comment by gep13** [comment]
@bryanmacfarlane I have asked the question if the typescript package should be modified to only use the LTS version of node.

**Comment by bryanmacfarlane** [comment]
Thanks.  And yes it should.  It should probably check to see if a version > min is already installed and in the path.  We will probably just switch to npm install typescript -g since the choco pkg offers little value past that (we already pull node ahead of that)

**Comment by AdmiringWorm** [comment]
> It should probably check to see if a version > min is already installed and in the path.

Unfortunately not a way to do this yet. the dependency of nodejs is resolved by chocolatey itself, before control is handled to the install script of the package.

There is a workaround though, install the package like this:
`choco install typescript --ignore-dependencies`.
This way choco won't try to resolve any dependencies of the package at all.

**Comment by AdmiringWorm** [comment]
SMall updated, just started a update process for the typescript package.
It has now been changed to depend the nodejs-lts package instead, and should be available on chocolatey.org in a few hours.

**Comment by evanportwood** [comment]
It seems odd that the agent wouldn't default to the LTS version and use the node tool installer task if you want the latest version.  Maybe this was the "rip off the band-aid" moment, but I'm curious as to how many builds this broke.

**Comment by bryanmacfarlane** [comment]
@AdmiringWorm - sounds great to depend on nodejs-lts.  That centralizes the thing to get right.  Thanks!

**Comment by neel015** [comment]
My build broke because of this update to Node v 10.0.0
The version 10.0.0 has a bug
[](https://github.com/nodejs/node/issues/20258)
The node tool installer is a solution to this- but can the new image point to the latest version of node which is v 10.1.0- Node claims that they have resolved the issue in this version.

**Comment by densto88** [comment]
@neel015 You can also use the Node tool installer as Bryan mentioned above to pin to the version you need in the meantime (or in general if you don't want to be impacted by future issues like this).

**Comment by deniztasdogen** [comment]
As this issue is closed, is it back to Node LTS (8.11) version?
