### ISSUE TITLE
WinRM never comes available....

### ISSUE THREAD

**Issue by klabranche** [Microsoft/vsts-image-generation#136]
I'm following the Build the VS2017Image docs (https://github.com/klabranche/vsts-image-generation/blob/master/docs/vs2017.md) and on the Use Packer to build and deploy the VM image template section, step 4 (run packer command), hangs on Waiting for the WinRM to become available....

Output from packer.exe build...

==> vhd: Running builder ...
    vhd: Creating Azure Resource Manager (ARM) client ...
==> vhd: Creating resource group ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-ZZZ'
==> vhd:  -> Location          : 'West US'
==> vhd:  -> Tags              :
==> vhd: Validating deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-ZZZ'
==> vhd:  -> DeploymentName    : 'pkrdpZZZ'
==> vhd: Deploying deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-ZZZ'
==> vhd:  -> DeploymentName    : 'kvpkrdpZZZ'
==> vhd: Getting the certificate's URL ...
==> vhd:  -> Key Vault Name        : 'pkrkvZZZ'
==> vhd:  -> Key Vault Secret Name : 'packerKeyVaultSecret'
==> vhd:  -> Certificate URL       : 'https://pkrkvZZZ.vault.azure.net...'
==> vhd: Setting the certificate's URL ...
==> vhd: Validating deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-ZZZ'
==> vhd:  -> DeploymentName    : 'pkrdpZZZ'
==> vhd: Deploying deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-ZZZ'
==> vhd:  -> DeploymentName    : 'pkrdpZZZ'
==> vhd: Getting the VM's IP address ...
==> vhd:  -> ResourceGroupName   : 'packer-Resource-Group-ZZZ'
==> vhd:  -> PublicIPAddressName : 'pkripZZZ'
==> vhd:  -> NicName             : 'pkrniZZZ'
==> vhd:  -> Network Connection  : 'PublicEndpoint'
==> vhd:  -> IP Address          : '123.123.123.123'
==> vhd: Waiting for WinRM to become available...

I've tried it a few times but eventually it dies when it hits the 4 hour timeout specified in the json file.

**Comment by lokesh755** [comment]
Can you check the packer logs ? Also, check your Azure VM security settings which might have rules to block particular ports due to which packer might not work as expected. If you find any packer specific issue due to which WinRM is not reachable, you can raise issue on packer repo https://github.com/hashicorp/packer.

**Comment by klabranche** [comment]
Logs show:
[INFO] Attempting WinRM connection...
2018/05/14 15:43:45 packer.exe: 2018/05/14 15:43:45 [DEBUG] connecting to remote shell using WinRM
2018/05/14 15:44:06 packer.exe: 2018/05/14 15:44:06 [ERROR] connection error: unknown error Post https://X.X.X.X:5986/wsman: dial tcp X.X.X.X:5986: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2018/05/14 15:44:06 packer.exe: 2018/05/14 15:44:06 [ERROR] WinRM connection err: unknown error Post https://X.X.X.X:5986/wsman: dial tcp X.X.X.X:5986: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2018/05/14 15:44:11 packer.exe: 2018/05/14 15:44:11 [INFO] Attempting WinRM connection...
2018/05/14 15:44:11 packer.exe: 2018/05/14 15:44:11 [DEBUG] connecting to remote shell using WinRM

**Comment by bryanmacfarlane** [comment]
Any firewalls or proxies in the way?

**Comment by klabranche** [comment]
Thanks for the reminder, I've since discovered that our org has closed that port down.  I'll close this issue.

**Comment by majorvin** [comment]
@klabranche  do you remember what port it wwas? Im getting the same issue.
