### ISSUE TITLE
Mac Hosted & Android AVDs

### ISSUE THREAD

**Issue by claudiosvcc** [Microsoft/vsts-image-generation#138]
I'm trying to create & start an AVD for running my tests on Hosted MAC machines.

Problem it's getting stuck on license agreement for installing the sdk:
2018-05-15T07:43:52.1438560Z Review licenses that have not been accepted (y/N)? 
./sdkmanager "system-images;android-26;google_apis;x86"
Tried to pipe 'y' and sdkmanager --license but nothing seems to work.
I'm running those from a "Shell script"
Maybe sdk should be pre-installed in the image with licenses agreed.

my final goal is to create an AVD this way
android create avd -n myavd -d 29 -k 'system-images;android-27;google_apis;x86'

Is there a way to get unblocked on this? any recomendation with any existing system-image that's already installed?

thanks

**Comment by ncouraud** [comment]
Hey Claudio,

We don't have any of the images installed by default, but it should be self-installable. I was able to create an AVD using the following steps in the hosted pool: 
```
$ANDROID_HOME/tools/bin/sdkmanager "system-images;android-26;google_apis;x86"
$ANDROID_HOME/tools/bin/avdmanager create avd -n myavd -d 29 -k "system-images;android-26;google_apis;x86"
```
from there an `$ANDROID_HOME/tools/emulator -avd myavd` booted my emulator just fine.

**Comment by claudiosvcc** [comment]
Thanks, indeed that worked.
The difference was I was "cd $ANDROID_HOME/tools/bin" and calling sdkmanager from there.
I have no idea why it should make any difference, though.
