### ISSUE TITLE
Add new Windows image for building 1803 based containers

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/vsts-image-generation#144]
Azure Sku Info
"publisher": "MicrosoftWindowsServer",
"offer": "WindowsServerSemiAnnual",
"sku": "Datacenter-Core-1803-with-Containers-smalldisk",
"version": "latest"

**Comment by artisticcheese** [comment]
I can not build 1709 images either. Is agent running LTS version of Windows?
