### ISSUE TITLE
VS2017 - Add Docker image microsoft/mssql-server-windows-developer

### ISSUE THREAD

**Issue by willgarcia** [Microsoft/vsts-image-generation#146]
Would it be possible to add the Docker image `microsoft/mssql-server-windows-developer` to the list of available images here: https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Vs2017/Update-DockerImages.ps1#L22
?

The size of this image is of ~15Go which takes time to download at the build time. VSTS builds being triggered on different VS2017 hosted agents, there's no possible re-use of the Docker cache. 

As we would prefer not to build/maintain our own custom agent, it would be good to add this Docker image to the list of default ones.

I'm not sure about the work required (a Packer build?). If it's literally just adding a Docker image and documentation, I'm happy to PR it.

**Comment by bryanmacfarlane** [comment]
The biggest consideration isn't the work to add - it's disk space budget.  Right now we have 128GB total and between VS, other tools leaving build space (10GB+), I don't believe there's room for 15GB.  We are looking at creating a bare windows core image with just cached images.  We will keep this open for consideration.

Another note - we are starting to experiment with bring your own subscription - pick / extend image, provide azure sub and we will spin up/shutdown (pay by minute) based on demand / config

**Comment by willgarcia** [comment]
Interesting. And at your scale, I can understand the disk space vs cost problem.

Having packaged Linux OS images in the past for CI systems, I'm actually not a big fan of having pre-installed tools or in this case pre-cached Docker images in an OS CI image, especially if "Docker is all I need" on my system. It tends to make images heavy, and static (due to the fixed versions of all the tools installed on it). I tend to prefer the approach of having Docker only and run containers to build/run tests in complete isolation (no need to deal with versions of npm/maven/etc on my CI host).

Another similar concern for me is the version of Docker installed on the VSTS host vs the one I will use in production.

In the meantime, I'll probably try these 2 approaches:
- the current AKS / VSTS integration (https://almvm.azurewebsites.net/labs/vstsextend/kubernetes/#setting-up-the-environment), so that I can run my services in prod-like conditions (=in a Kubernetes cluster in this case).
- worst case scenario: build my own image

I'm a complete beginner with Azure, so thanks for helping. Happy to know more about your new model (extend images/pay by minute).

Please close there's no easy solution to this request!

**Comment by willgarcia** [comment]
A last question maybe @bryanmacfarlane : would you be able to (un)confirm that - apart from the pre-pulled Docker images on the OS image - there's no supported way to re-use Docker layers caching across multiple builds?

I could not find this info in the docs, so that'd be helpful info.

**Comment by bryanmacfarlane** [comment]
currently, for hosted build it's a fresh machine every time so you won't get any benefits from docker layers since very build will pull the full cache.  we've considered 'leasing' and mounting a disk between different builds.

The other thing that we're experimenting with is Kubernetes as build infra.  Point us at your AKS or other kubernetes instance ...  That would be a new pool type.

**Comment by densto88** [comment]
@willgarcia there's a UserVoice suggestion [here](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/32044321-improve-hosted-build-agent-performance-with-build) that you can vote on and add your ideas to if they aren't already represented there.

**Comment by willgarcia** [comment]
Closing (Won't directly fix)
