### ISSUE TITLE
Unable to deploy tabulars without missing executable

### ISSUE THREAD

**Issue by cnyborg** [Microsoft/vsts-image-generation#147]
The closed issue #105 did not receive a proper solution.

When building Tabular-projects i end up with .asdatabase files, these need to be built into .xmla with: <code>C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe</code>

That solution was disliked, which I can agree with. But if SSMS not is the solution, what is?

**Comment by bryanmacfarlane** [comment]
Closing as a dupe, re-opened the other.  Gave a proper solution until we find another way.
