### ISSUE TITLE
Request: Update AzureRM to 6.1.1

### ISSUE THREAD

**Issue by drewsac** [Microsoft/vsts-image-generation#149]
Is there any timeframe for the update of AzureRM that are available on hosted 2017 agents?  We are specifically waiting on several features only available in newer versions:
1) Get keys from Azure SignalR (in preview but requires a newer version of AzureRM.Profile)
2) Get the identity of an app service/function that has Managed Service Identity enabled ([see issue 4808](https://github.com/Azure/azure-powershell/issues/4808))

**Comment by AlexKeySmith** [comment]
Hi, I've devised a workaround if anyone is interested: https://stackoverflow.com/a/50739203/141022

**Comment by AlexKeySmith** [comment]
Hi, any word if this is likely to be a candidate in a future release?

Unfortunately although my workaround is pretty reliable it does take up quite a percentage of time in our releases.

Ideally we wouldn't want to manage our own agents, preferring PaaS wherever we can.

I'd submit a PR, but as far as I can tell the AzureRM module is installed from a private blob storage when the machine image is created, I'm guessing this is done to keep this build process reliable / quick if powershellgallery is down?

Perhaps the project could instead use a VSTS nuget cache proxy thingamajig to empower the community to be able to do upgrade PR's?

**Comment by SumiranAgg** [comment]
@samuelbcollie We will be upgrading to latest powershell version.

**Comment by MichelZ** [comment]
Question is WHEN :)

**Comment by lokesh755** [comment]
Added AzureRM 6.7.0 on Hosted VS2017 agent
