### ISSUE TITLE
Problem with updating Android SDK

### ISSUE THREAD

**Issue by mkruczkowski** [Microsoft/vsts-image-generation#150]
Android SDK tools on hosted agents are outdated and updating them is very problematic.

## Agent Version and Platform
2.134.2
Windows
(it occurs on both "Hosted" and "Hosted VS2017" agents)

## VSTS Type
VisualStudio.com

## What's not working?
While running PowerShell script with line:
`echo y | & "$env:ANDROID_HOME\tools\android.bat" update sdk -u -a -t tools,platform-tools,build-tools-27.0.3,android-27,extra-google-m2repository,extra-android-m2repository`

SDK update hangs with this message:
```
[...]
Installing Android SDK Tools, revision 25.2.5
  Failed to rename directory C:\java\androidsdk\android-sdk\tools to C:\java\androidsdk\android-sdk\temp\ToolPackage.old01.
SDK Manager: failed to install
-= Warning ! =-
A folder failed to be moved. On Windows this typically means that a program is using that folder (for example Windows Explorer or your anti-virus software.)
Please momentarily deactivate your anti-virus software or close any running programs that may be accessing the directory 'C:\java\androidsdk\android-sdk\tools'.
[...]
```

Without this update, I cannot accept the licences (it's the second issue) because below error occurs on build start:

```
File C:\Users\buildguest\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 27.0.3 in C:\java\androidsdk\android-sdk\licenses
Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
Checking the license for package Android SDK Platform 27 in C:\java\androidsdk\android-sdk\licenses
Warning: License for package Android SDK Platform 27 not accepted.
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.google.auto.value:auto-value:1.3', 'com.ryanharter.auto.value:auto-value-parcel:0.2.5' and apply the kapt plugin: "apply plugin: 'kotlin-kapt'".
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27, Android SDK Build-Tools 27.0.3].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

and I cannot use simple `sdkmanager --licenses` because android tools version is too low.

These packages should be updated:
```
Available Updates:
   ID                                                  | Installed | Available
   -------                                             | -------   | -------  
   extras;android;m2repository                         | 45.0.0    | 47.0.0   
   extras;google;google_play_services                  | 39.0.0    | 49       
   extras;google;m2repository                          | 44.0.0    | 58       
   extras;intel;Hardware_Accelerated_Execution_Manager | 6.0.4     | 6.2.1    
   platform-tools                                      | 25.0.3    | 27.0.1   
   tools                                               | 25.2.5    | 26.1.1   
```

**Comment by madhurig** [comment]
@mkruczkowski: We are no longer updating the "Hosted" VMs. We recently added 27.0.3 to the "Hosted VS2017" VMs. Can you provide the error logs on "VS2017"? What version of Android SDK and Gradle are you using in your project?

Thanks,
Madhuri

**Comment by mkruczkowski** [comment]
@madhurig There was added version `27.0.3` of android `Build-Tools` but `tools` and `platform-tools` are still outdated and because of this we cannot accept the licences.
Please update these two also.

I'm using:
`gradle:3.0.1`
`compileSdkVersion 27`
 `buildToolsVersion '27.0.3'`

**Comment by madhurig** [comment]
@mkruczkowski: I was able to run update successfully using a command line script on the "Hosted VS 2017" VMs:

echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools,platform-tools,build-tools-27.0.3,android-27,extra-google-m2repository,extra-android-m2repository
[1_Job.txt](https://github.com/Microsoft/vsts-image-generation/files/2063926/1_Job.txt)

I am also able to run a gradle build targeting SDK 27 using build tools 27.0.3 without updating the SDK or accepting licenses. I compared the licenses we have pre-installed on the VMs with the latest ones and they match, so you should not need to accept licenses when running your build. 

Let us know if you are still seeing issues with "Hosted VS 2017" VMs. 

Thanks,
Madhuri

**Comment by mkruczkowski** [comment]
> I was able to run update successfully [...]

In the file that you attach I can find such error:

```
[...]
2018-06-01T19:18:33.9436858Z SDK Manager: failed to install
2018-06-01T19:18:33.9437072Z -= Warning ! =-
2018-06-01T19:18:33.9437284Z A folder failed to be moved. On Windows this typically means that a program is using that folder (for example Windows Explorer or your anti-virus software.)
2018-06-01T19:18:33.9437566Z Please momentarily deactivate your anti-virus software or close any running programs that may be accessing the directory 'C:\Program Files (x86)\Android\android-sdk\platforms\android-27'.
2018-06-01T19:18:33.9437794Z When ready, press YES to try again.
2018-06-01T19:18:33.9437972Z Note: you  can use --force to override to yes.
2018-06-01T19:19:35.6014760Z [y/n] =>    Unexpected Error installing 'SDK Platform Android 8.1.0, API 27, revision 3': java.lang.StringIndexOutOfBoundsException: String index out of range: -1
2018-06-01T19:19:35.6019486Z Error: Unexpected Error installing 'SDK Platform Android 8.1.0, API 27, revision 3': java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[...]
```

This is exactly what I get when I'm running the above command.
That means that you do not update successfully.
In timestamps, I can see that you just wait an hour to pass it through (and just skip installation of this component). It's not acceptable for me because I do not have such amount of time (and I do not want to skip anything).

However, now I can build my project without accepting licenses so the main issue seems to be fixed somehow.
I have not done anything so I don't know why it started to work.

The issue can be closed I think.
