### ISSUE TITLE
Request new version of Azure CLI

### ISSUE THREAD

**Issue by nwohlgemuth** [Microsoft/vsts-image-generation#160]
There is a bug in Azure CLI version 2.0.32 that affects 'az storage entity query' and prevents any successful use of that command. This issue has been fixed in version 2.0.33 via https://github.com/Azure/azure-cli/pull/6355. The VSTS agent currently has 2.0.32 installed and is blocking us from being able to run releases. Is there any way to upgrade the Hosted agent to pick up the new version? We are using both 'Hosted VS2017' and 'Hosted Linux' and this issue is affecting both hosts.

**Comment by bryanmacfarlane** [comment]
The builds run as admin so you could potentially run the same code (script) in your build that we run as part of image generation?? 

https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Install-AzureCli.ps1

https://github.com/Microsoft/vsts-image-generation/blob/users/dakale/linux/images/linux/scripts/installers/azure-cli.sh

just not sure if choco and apt-get has the new version 2.0.33

**Comment by nwohlgemuth** [comment]
Thanks for the response!
apt-get has version 2.0.33 so we were able to use that to fix it for Linux.
For Windows, choco does not yet have version 2.0.33 unfortunately. We were able to get around that by downloading and running the Azure CLI installer directly.
Batch script to do that:
powershell (new-object System.Net.WebClient).DownloadFile('https://aka.ms/installazurecliwindows', '%TEMP%\\az_cli.msi') 
%TEMP%\\az_cli.msi /quiet /norestart 
del %TEMP%\\az_cli.msi 

Powershell script to do that:
(new-object System.Net.WebClient).DownloadFile('https://aka.ms/installazurecliwindows', "$
env:temp\\az_cli.msi")
Start-Process "$env:temp\\az_cli.msi" "/quiet /norestart"
Remove-Item -path "$env:temp\\az_cli.msi"
