### ISSUE TITLE
Install Slacker on Hosted VS2017 image

### ISSUE THREAD

**Issue by muralikarumuru** [Microsoft/vsts-image-generation#163]
To run sql database unit test using slacker framework on Hosted VS2017 image, the build agent must have the slacker framework installed for successful unit test execution.

Below are the steps for installing slacker on build machine. Please see the link for slacker framework install. https://github.com/erickangMSFT/dbunittest-slacker/blob/master/demo/setup.md

Ruby installation
Install runby 2.2.6

ruby_installer.exe -o "c:\Ruby" -y
Install ruby DevKit

ruby_devkit_installer.exe -o "c:\RubyDevKit" -y
It is a Self-extracting zip file. Create a folder e.g. RubyDevKit and extract devkit files.
Add RubyDevKit\bin to PATH.
Run following commands
cd rubydevkit
ruby dk.rb init
ruby dk.rb install
Install slacker
gem install slacker

**Comment by lokesh755** [comment]
I'm not very sure about the priority of installing slacker. But in mean time, you can create a powershell task as part of your build definition to install slacker with just one line "gem install slacker" since ruby is already installed on the hosted agents.

**Comment by bryanmacfarlane** [comment]
Agreed.  Since you are admin you can automate this as part of your build.  The other option is a private agent on an azure VM.

**Comment by muralikarumuru** [comment]
Thank you. I will add task in my build.
Thank you for your support.

Best regards,
Murali
