### ISSUE TITLE
.NET Core SDK 2.1.301

### ISSUE THREAD

**Issue by cheng93** [Microsoft/vsts-image-generation#168]
.NET Core SDK 2.1.301 is out

https://www.microsoft.com/net/download/windows

FWIW

```
error NU1608: Detected package version outside of dependency constraint: Microsoft.AspNetCore.App 2.1.0 requires Microsoft.AspNetCore.Authentication (= 2.1.0) but version Microsoft.AspNetCore.Authentication 2.1.1 was resolved.
```

Don't forget the readme https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#net-core

**Comment by petervandenhout** [comment]
I have a similar issue since I've upgraded my code to use core 2.1.1
```
error NU1107: Version conflict detected for Microsoft.AspNetCore.
```

**Comment by steve-sword** [comment]
I had to switch from a version-less reference to an explicit reference in the .csproj project:

<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />

**Comment by petervandenhout** [comment]
@steve-sword adding `Version="2.1.1"` also did the trick for me, thanks!

**Comment by natemcmaster** [comment]
@steve-sword's recommendation is the best solution until VSTS updates their SDK. After lots of feedback and issues like this one, we are not recommending the version-less PackageReference anymore. We are working on removing support for the versionless PackageReference from new project templates and docs (see https://github.com/aspnet/Home/issues/3292). 

:warning: **Please be aware that updating the PackageReference may cause your web applications to fail to start** when the deployment server only has the 2.1.0 runtime. You must have the 2.1.1 runtime installed on the machine to run apps referencing the 2.1.1 metapackage.

We realize this is a confusing experience, and are looking to completely remove the PackageReference altogether from the .csproj files. We are currently discussing what this may look like and I can't give a timeline for when this might land. Please see https://github.com/aspnet/Home/issues/3307 for discussion.

**Comment by lokesh755** [comment]
Updated .NET core sdks on VSTS hosted agents
