### ISSUE TITLE
Validate-ToolCache.ps1 fails because Python is updated from 3.7.0-b2 to 3.7.0 in Tool Cache

### ISSUE THREAD

**Issue by ryanspletzer** [Microsoft/vsts-image-generation#172]
The Python 3.7.0-b2 beta has been updated to the released 3.7.0 version from June 27 in the Tool Cache download.

https://www.python.org/downloads/release/python-370/

But Validate-ToolCache.ps1 is still checking for the 3.7.0-b2 version, thus it fails and exits.

I've submitted #171 PR to fix.

**Comment by lokesh755** [comment]
Thanks for submitting PR. Tool cache is updated just this week. We've other PR to resolve this. https://github.com/Microsoft/vsts-image-generation/pull/170 which I merged

**Comment by ryanspletzer** [comment]
@lokesh755 Cools thanks, sorry missed that other PR!
