### ISSUE TITLE
Add Chrome for testing to Linux preview image

### ISSUE THREAD

**Issue by stewx** [Microsoft/vsts-image-generation#181]
We are loving the Chrome support that has been added for the Windows agents (Hosted VS2017). We need it for running unit tests for our web project. We would like to have the same support added to the hosted Linux preview agent, preferably with the environment variable CHROME_BIN pointing to the binary so our tools can automatically pick up the location.

**Comment by dakale** [comment]
Do you just need Chrome or the Selenium ChromeDriver as well? It looks like all we install on Windows is Chrome, but I am unsure of exactly what you need

**Comment by stewx** [comment]
@dakale Just Chrome for me, personally, but others may want the Selenium driver.

**Comment by dakale** [comment]
I added the `google-chrome` package: https://github.com/Microsoft/vsts-agent-docker/commit/cf55875fb42b55a0f68419df844b2d90d4d40e19

Ill close this when it is deployed to hosted pools, but the updated images are pushed and you can try them out if you run it as a private agent

**Comment by stewx** [comment]
Not active on our hosted agent yet:

![image](https://user-images.githubusercontent.com/6986171/43959005-a9d94ad2-9c83-11e8-9d0c-2d8c448cd2b0.png)

**Comment by stewx** [comment]
Maybe we just need to update ours. Never mind.

**Comment by dakale** [comment]
The Hosted Linux Preview pools have been updated. Let me know if you have any issues.
