### ISSUE TITLE
Git out of date on Ubuntu 16.04 image

### ISSUE THREAD

**Issue by vtbassmatt** [Microsoft/vsts-image-generation#184]
We need a Git newer than 2.7.4 on the Ubuntu 16.04 image. Doesn't have to be bleeding edge, but something post-2.9. Ideally, 2.18 :)

**Comment by dakale** [comment]
I recently added a Git installer to overwrite the factory Git version: https://github.com/Microsoft/vsts-image-generation/commit/f9b582e5a500d4c1ac388e5e5a1d5bef3e1b9950#diff-2a80e84053b2ec1114fc4147aaafd4bd

Heres the metadata for the currently built but not deployed image: https://github.com/Microsoft/vsts-image-generation/blob/master/images/linux/Ubuntu1604-README.md

I will leave this open until the hosted pool is updated

**Comment by vtbassmatt** [comment]
Thank you!

**Comment by dakale** [comment]
Ive started deploying a new image to Hosted Ubuntu 1604 pools, you should see this change roll out over the next few days
