### ISSUE TITLE
In the Windows templates, the sysprep step is looking for unattend.xml at an incorrect path

### ISSUE THREAD

**Issue by MathieuBuisson** [Microsoft/vsts-image-generation#190]
Hi,

This issue is regarding the following templates :  

  - images/win/WindowsContainer1803-Azure.json
  - images/win/vs2015-Server2012R2-Azure.json
  - images/win/vs2017-Server2016-Azure.json

In all these templates, the last provisioning step is generalizing (sysprep) the image, and the first line of this provisioning step is :  
`"if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}"`  

I'm fairly sure that this path is incorrect because on most systems, `$Env:SystemRoot` resolves to : `C:\WINDOWS`.  

So I think that the 2 occurrences of :  
`$Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml`  
should be replaced by :  
`$Env:SystemRoot\\System32\\Sysprep\\unattend.xml`  

If you agree, I can make a pull request to include the change mentioned above.  
Thank you.

**Comment by lokesh755** [comment]
makes sense.
