### ISSUE TITLE
Missing hosted tools cache

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-image-generation#192]
Ruby, Python, etc. are not available on Hosted Ubuntu 1604 because they aren't found in the tools cache.  Example build message:

```
2018-08-09T20:27:52.2745935Z ##[error]Version spec >= 3.7.0a for architecture x64 did not match any version in the tool cache.
Available versions:
<none>
```

Here's a build that Yash could give you access to:
https://yaananth.visualstudio.com/pythondemo/_build/results?buildId=2467&_a=summary&view=logs

**Comment by DavidStaheli** [comment]
It looks like PHP is also missing, though PHP isn't installed through the tools cache.  It has its own installation in vsts-agent-docker's Dockerfile.

**Comment by dakale** [comment]
Is the hosted tools cache located via the environment? In Hosted Linux Preview / Docker there is `ENV AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache` but it is not in the Hosted Ubuntu environment. Other than that, it looks like everything should be installed the same. 

See https://github.com/Microsoft/vsts-image-generation/blob/master/images/linux/scripts/installers/hosted-tool-cache.sh vs https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/standard/Dockerfile.template#L417

**Comment by vtbassmatt** [comment]
David's list that he's noticed so far:

- docker
- docker-compose
- gradle
- python
- PHP
- Ruby

**Comment by dakale** [comment]
This should be resolved now. Open a new issue if any specific issues occur
