### ISSUE TITLE
Help for adding chrome in Windows

### ISSUE THREAD

**Issue by maysamms** [Microsoft/vsts-image-generation#193]
Hello!

I saw that there are images to be able to add the chrome in hosted vs2017. However, I have never done this ... I am using hosted to be able to study about the build :(

Would anyone know and could help me perform the installation on my hosted? I need it and seleniumwebdrivers

I tried to add the .ps1 as powershell in the build (I do not know if it was the right thing to do) but it depends on psm1 and psd1 that are not running because it returns the error that ps1 is required :( and trying to add as inline, displays the error below:

At D:\a\_temp\4f3f6c95-1fb1-4dbc-b391-dff13b8baa53.ps1:2 char:1
 + [CmdletBinding()]
 + ~~~~~~~~~~~~~~~~~
 Unexpected attribute 'CmdletBinding'.
 At D:\a\_temp\4f3f6c95-1fb1-4dbc-b391-dff13b8baa53.ps1:3 char:1
 + param()
 + ~~~~~
 Unexpected token 'param' in expression or statement.
 At D:\a\_temp\4f3f6c95-1fb1-4dbc-b391-dff13b8baa53.ps1:3 char:7
 + param()
 +       ~
 An expression was expected after '('.
     + CategoryInfo          : ParserError: (:) [], ParseException
     + FullyQualifiedErrorId : UnexpectedAttribute

I do not know how to do

**Comment by lokesh755** [comment]
You need to add .ps1 content. For reference.. https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Install-Chrome.ps1
