### ISSUE TITLE
linux image uses docker test instead of stable

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/vsts-image-generation#206]
https://github.com/Microsoft/vsts-image-generation/blob/c2bade1d39495ed4e0f96f4a73054cb54164c7df/images/linux/scripts/installers/docker-ce.sh#L23

Is there a reason not to use the stable channel? I'm facing troubles on the docker sock that might relate to the TP release of docker. After switching to stable we were able to connect to the docker sock again. These problems started last week, probably since the [18.09 pre-release](https://github.com/docker/docker-ce/releases/tag/v18.09.0-ce-tp0).

Also see https://github.com/Microsoft/vsts-image-generation/issues/40 which mentions `stable` but doesn't include any commits.

**Comment by dakale** [comment]
Okay, this was a holdover from when the image was based on Ubuntu 18 which did not have a stable release. Updating to stable on 16
