### ISSUE TITLE
./scripts/Install-Python.ps1 - Select-String : Cannot bind argument to parameter 'Pattern' because it is null.

### ISSUE THREAD

**Issue by marvinpuethe** [Microsoft/vsts-image-generation#28]
# Intro

Hi, 
I've tested the VSTS Image Generation with the Windows VS 2017 Image. Unfortunately I get the described error when executing ./Install-Python.ps1. Maybe I'm doing something wrong so I've described the repro steps.

Thanks in advance for your help.

Greetings from Germany,
Marvin

# Description

When running packer with the Windows VS2017 Image provisioning a vhd Image to Azure, `Install-Python.ps1` returns `Select-String : Cannot bind argument to parameter 'Pattern' because it is null.`

# Repro Steps

1. Clone repository. 
1. Cd into `images\win\Vs2017`.
1. Remove builder `managed-disk` to reduce execution time.
1. Because I tested in Dev Essentials and Quota limits cores to 4: 
Change row 12 in `images\win\Vs2017\vs2017-Server2016-Azure.json` to 
`"vm_size": "Standard_DS3_v2",`
1. Create `windows.json` with:
```
{
    "client_id": "<spn.applicationId>",
    "client_secret": "<spn_password>",
    "subscription_id": "<spn.subscriptionId>",
    "tenant_id": "<spn.tenantId>",
    "object_id": "<spn.Id>",
    "resource_group": "<capture_rg>",
    "storage_account": "<capture_storage_account>",
    "location": "<rg location>"
}
```
By the way: There is a missing comma after `"<capture_storage_account>"` in the ReadMe file.

6. Execute `packer build -var-file="windows.json" -var "commit_id=$(g
it log --pretty=format:'%H' -n 1)" .\vs2017-Server2016-Azure.json`

# System Info

Windows: 10 1709 Build 16299.125
Powershell: 5.1 Build 16299.98
Azure Subscription: Dev Essentials

# Log
Complete log -> [complete-log.txt](https://github.com/Microsoft/vsts-image-generation/files/1565070/complete-log.txt)

```
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: ./scripts/Install-Python.ps1
    vhd: ;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager
    vhd: Select-String : Cannot bind argument to parameter 'Pattern' because it is null.
    vhd: At C:\Windows\Temp\script-5a352c9e-73b0-9e6b-89dc-cd081e5fc421.ps1:21 char:47
    vhd: + if ($currentPath | Select-String -SimpleMatch $pythonDir.FullName)
    vhd: +                                               ~~~~~~~~~~~~~~~~~~~
    vhd:     + CategoryInfo          : InvalidData: (:) [Select-String], ParameterBindingValidationException
    vhd:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SelectStrin
    vhd:    gCommand
    vhd:
    vhd: ERROR: Invalid syntax.
    vhd: Type "SETX /?" for usage.
==> vhd:
==> vhd: Cleanup requested, deleting resource group ...
==> vhd: Resource group has been deleted.
Build 'vhd' errored: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```

**Comment by lokesh755** [comment]
Hi Marvin,

           In the Install-Python.ps1 script we're just adding the python path to machine path. But the python is initially installed while VS2017 installation. Unfortunately in new release of VS2017 , the installation path of python has been changed, due to which the current script is failing. I've made the changes to python path. But still the build might fail since "Install-AzureModules.ps1" will also fail due to some other reason. I am currently working on fixing it. But if you're not using azure-modules, you can simply remove "Install-AzureModules.ps1" and "Validate-AzureModules.ps1" from the vs2017-Server2016-Azure.json.
