### ISSUE TITLE
Error installing Install-AzureModules.ps1 

### ISSUE THREAD

**Issue by lokesh755** [Microsoft/vsts-image-generation#30]
Following error is thrown while executing Install-AzureModules.ps1

`2017-12-18T03:28:00.0407619Z 1513567680,,ui,message,    vhd: An Azure PowerShell Installation through installer has been detected and it does not have a version 2.1.0. Please close this powershell session and manually uninstall the Azure PowerShell from the Add or Remove Programs in the Control Panel. Then%!(PACKER_COMMA) rerun this script from an Admin PowerShell`

Attached complete log file for reference ..

[Run Packer build.txt](https://github.com/Microsoft/vsts-image-generation/files/1568352/Run.Packer.build.txt)

**Comment by niadak** [comment]
@lokesh755 , As the error message indicates, Azure PowerShell (version != 2.1.0) is already installed on the machine. The pre-reqs for the script to work is no Azure PS other than 2.1.0 is installed on the machine. User should uninstall Azure PS and try to run the scripts again.

Please let us know if the above Pre-Reqs is not expected and we need to handle this case in more reliable way.

**Comment by lokesh755** [comment]
@niadak . It seems Visual studio now installs the latest version of Azure-Powershell which is 5.0.0 which is causing the script to fail. I feel it might be better to modify the Install-AzureModules.ps1 script to accommodate this change.

**Comment by niadak** [comment]
Thanks Lokesh for providing the info. We will update the script accordingly.

**Comment by chrisrpatterson** [comment]
@niadak this issue is still open as the validation script for the Azure modules fails.
