### ISSUE TITLE
Mark Releases properly in the Repo so that customers can monitor them via RSS

### ISSUE THREAD

**Issue by densto88** [Microsoft/vsts-image-generation#31]
In addition to creating a release branch for each released image (to support effective hotfixing) we should create a Release here in the GitHub Repo so that customers can monitor changes to the images via their RSS Feeds.

**Comment by lokesh755** [comment]
Thanks for the input. Chris created release on Github repo and also will make sure to create releases in future.

**Comment by densto88** [comment]
Linking the [created Release](https://github.com/Microsoft/vsts-image-generation/releases/tag/1712)
