### ISSUE TITLE
Install SQL Local DB on Windows images

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/vsts-image-generation#34]
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-2016-express-localdb

**Comment by StefanSchoof** [comment]
There is an Issue with Hosted Builds since December. See [https://stackoverflow.com/questions/47818059](VSTS and LocalBD: Failed to update database XXX because the database is read-only). Is this related?

**Comment by chrisrpatterson** [comment]
@StefanSchoof  maybe, we are looking into it.

**Comment by lokesh755** [comment]
SQL Server Express 2016 LocalDB is already installed by Visual studio 2017.
