### ISSUE TITLE
Add latest windows docker images to agent

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vsts-image-generation#39]
For anybody building docker images on hosted agent it's known that most time consuming task is to download base images to agent. Please add base images for servercore and nanoserver to agent.

**Comment by Dweston88** [comment]
This would be very helpful. +1

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017/scripts/Update-DockerImages.ps1

**Comment by artisticcheese** [comment]
How does script help for hosted VS2017 agent? It initialized from scratch each time it's called, right? So this images has to be pulled each time it spins up.

**Comment by lokesh755** [comment]
Images are generated and stored. Only stored image is used for spinning up VM. So scripts will not run every time.

**Comment by artisticcheese** [comment]
How do one know when hosted agents are updated with latest images? Path Tuesday was yesterday but VSTS hosted agents are still running old docker images.

**Comment by lokesh755** [comment]
You can look into releases. The current update is still in "Pre-release" status. https://github.com/Microsoft/vsts-image-generation/releases/tag/1803

**Comment by artisticcheese** [comment]
So how long usually does it take to get latest images into image after being posted on docker hub?

**Comment by lokesh755** [comment]
It depends on the time we generate the image. While we generate we get the latest available. We usually generate image 1-3 times a month.
