### ISSUE TITLE
Upgrade to the latest .NET Core runtime/sdk

### ISSUE THREAD

**Issue by RubenDelange** [Microsoft/vsts-image-generation#45]
## Agent version and platform
Version of your agent? 2.126.0 (Hosted VS2017)
OS of the machine running the agent? Windows

## VSTS type and version
VisualStudio.com

## What's not working?
The .NET Core runtime/sdk version on our build agent is currently 2.0.3 (dotnet --info). Is there a way to upgrade to the latest 2.1.4 SDK ~ 2.0.5 runtime version (cfr. security fixes)?
Or do we have to wait until the build agents are upgraded?

Thanks in advance!

**Comment by lokesh755** [comment]
New image was generated this week with latest version of .NET  Core 2.0.5. It's being updated on VSTS probably by this weekend.

**Comment by RubenDelange** [comment]
Great, thanks a lot!

**Comment by chrisrpatterson** [comment]
@RubenDelange you can also install the .NET Core framework on the fly using the .NET Installer task.
