### ISSUE TITLE
Support Chrome Headless

### ISSUE THREAD

**Issue by Davilink** [Microsoft/vsts-image-generation#47]
I don't know if i should post it here or elsewhere but here the problem, i want to use the Hosted Agent for our Pipeline, but we can't run any Karma test or Integration test (We use Angular in our project with .Net Core) because there not installed browser in the hosted Agent. I was going to use PhantomJS but i get 3 problem :
1. PhantomJS take a lot memory compare to Chrome in Headless mode
2. PhantomJS project will not be maintened : https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
3. Each time the pipeline will build our project (for each project), we will have to wait just to install PhantomJS (node module), it will cost time, memory and disk usage for something IMO should be by default in the hosted Agent.

Do you think i will be possible to add the Chrome Browser in the Hosted Agent ?
The Headless mode let use chrome in a windowsless environnement, so perfect for CI Agent.

**Comment by elvirdolic** [comment]
Would be amazing

**Comment by lokesh755** [comment]
We're planning to install Chrome and Firefox browsers on Hosted Agent in next release.

**Comment by lokesh755** [comment]
New image will be released by next week.

**Comment by chrisrpatterson** [comment]
There is a PR open to add all of the browsers https://github.com/Microsoft/vsts-image-generation/pull/61.  It has a few issues but as soon as it is merged we will get it into the pipeline.  Keep an eye on the release notes.

**Comment by Davilink** [comment]
I saw that the PR has been Merged. The only thing left is to updated the the file here : https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md

**Comment by sebastianhaas** [comment]
Hey! Is there a date where we can expect a new release containing the browsers?

**Comment by lokesh755** [comment]
Probably next week, we missed the browser install update in our last release of images.

**Comment by Davilink** [comment]
Is the file :  https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md will be updated ?

How can we know if the deployment of the new image has been done ?

**Comment by lokesh755** [comment]
It will updated. Deployment of new image is in progress. Once it's done we'll update the Readme doc.

**Comment by lokesh755** [comment]
Yup.. Readme is updated with latest info.

**Comment by stewx** [comment]
Love the support in Hosted VS2017. Can Chrome please also be installed on the Linux preview?

**Comment by stewx** [comment]
Added a new request for this on Linux: https://github.com/Microsoft/vsts-image-generation/issues/181
