### ISSUE TITLE
Upgrade to the latest Visual Studio Version

### ISSUE THREAD

**Issue by Richard-York** [Microsoft/vsts-image-generation#50]
Hi Team, 
When will we be updating the Hosted vs2017 Agent to the latest version of Visual Studio?
My team are currently using Language Pack 7.2 on version 15.5.4 and we are getting compile errors. 

Many Thanks

**Comment by lokesh755** [comment]
A new Hosted image is generated last week which has Visual studio version 15.5.3 installed. It's currently being updated on VSTS.

**Comment by lokesh755** [comment]
All hosted agents will be updated by end of the day today.

**Comment by Richard-York** [comment]
Thanks guys


Kind regards,

Richard York
Tech Support Manager

[cid:IoT--VectorLogo_IoT--LandscapeLogo_Mailer_1db731f0-0eb1-4b30-bb00-f861d255ffb0.png]<https://www.iotnxt.com/>


Address: Bylsbridge Office Park, Building 14, Block C, 1st Floor, Alexandra Road, Highveld Ext 73, Centurion, Gauteng, 0046, South Africa
Phone: +27 12 880 0114
Mobile: +27 82 924 3066
Email: richard.york@iotnxt.com<mailto:richard.york@iotnxt.com>
Website: https://www.iotnxt.com

[cid:facebook_7fa50cc5-bd2e-456e-b71e-bcc6975537f7.png]<https://www.facebook.com/iotnxt/> [cid:linkedin_de143d75-2ff5-460f-b904-2d40ec2e8b51.png] <https://www.linkedin.com/company/iot.nxt>  [cid:twitter_84ab30d9-fec7-4e63-bb5e-8291caf481e8.png] <https://twitter.com/iot_nxt>  [cid:youtube_7ef73685-9dd4-488f-8407-84b0638dac87.png] <https://www.youtube.com/channel/UC_T4pl8fw5xijduERcOtTzQ>  [cid:Location-Icon_68f5d1d7-c4ad-447e-8890-cfc8f35cf158.png] <https://bit.ly/2vzWxgi>


[cid:IoT.nxt_EmailSignature_b3016df6-f0f0-4f94-b5ca-8410604b990c.png]

Disclaimer: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Please notify the sender  richard.york@iotnxt.com<mailto:richard.york@iotnxt.com?subject=Disclaimer%20error,%20email%20received%20by%20mistake>  immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system.

On 23 Jan 2018, at 23:54, Lokesh Gopu <notifications@github.com<mailto:notifications@github.com>> wrote:


All hosted agents will be updated by end of the day today.
