### ISSUE TITLE
[Feature Request] Install WinAppDriver and the Microsoft Visual Studio 2017 Installer Projects extension

### ISSUE THREAD

**Issue by kuenzign** [Microsoft/vsts-image-generation#54]
My team is trying to get our UI tests to run and installer to build during a VSTS build on the Hosted VS2017 agent.  In order to do this, we need WinAppDriver (found here https://github.com/Microsoft/WinAppDriver/releases) and the Microsoft Visual Studio 2017 Installer Projects extension (found here https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2017InstallerProjects) to be installed.  Could this please be added?  Thank you.

**Comment by chrisrpatterson** [comment]
You are running as an admin on the VM so you should be able to install the software during your build as well.

**Comment by kuenzign** [comment]
Is there any documentation on installing software during a build?

**Comment by lokesh755** [comment]
You can look into the current repo on how to install Exe, MSI or VS extensions. You can create similar script as powershell task while you are executing a build to install any additional software required. 

For reference.. for installing MSI : https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Install-SQLPowerShellTools.ps1

**Comment by jawn** [comment]
@kuenzign Here's an example of installing a VS extension:
https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Vs2017/Install-Wix.ps1

**Comment by kuenzign** [comment]
Awesome, thanks!
