### ISSUE TITLE
VS 2015 install uses RTM link

### ISSUE THREAD

**Issue by mjring** [Microsoft/vsts-image-generation#60]
It looks like the **Install-VS2015.ps1** script only installs the RTM version. Is there a link to the VS 2015 w/ Update 3 install available?

Alternatively, how is VS 2015 Update 3 getting applied to the image otherwise? Is it getting applied via the Windows Updates script?

**Comment by lokesh755** [comment]
Current installer dynamically fetches the latest features. Run the installer manually and select "Custom", you can see "Visual Studio 2015 Update 3" at the top of the list.

**Comment by mjring** [comment]
Thanks for the confirmation Lokesh. This was a misunderstanding on my end. On my forked copy, I was modifying the repo to allow use of an AdminFile.xml, but was using an existing, outdated adminFile that didn't included components for VS 2015.3. So, in my testing, it was only installing RTM.

Re-gen'ing a new AdminFile based on this downloaded vs_enterprise.exe fixed the issue.

Sorry for the confusion!
