### ISSUE TITLE
Android SDK Licenses not installed on hosted agent

### ISSUE THREAD

**Issue by AlasdairSQR** [Microsoft/vsts-image-generation#63]
When using the Android template for a new build definition, it appears the Android SDK licenses are not installed on the hosted image.  Using the gradle build task gives the following output in the log:

```
Checking the license for package Android SDK Build-Tools 26.0.2 in C:\java\androidsdk\android-sdk\licenses
Warning: License for package Android SDK Build-Tools 26.0.2 not accepted.
Checking the license for package Android SDK Platform 26 in C:\java\androidsdk\android-sdk\licenses
Warning: License for package Android SDK Platform 26 not accepted.
BUILD FAILED
Total time: 1 mins 47.977 secs
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
.
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: d:\a\1\s\gradlew.bat failed with return code: 1
    at ChildProcess.<anonymous> (d:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\1.126.0\node_modules\vsts-task-lib\toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

A workaround was posted here, and this issue is marked as Closed, though the error is still being thrown: https://developercommunity.visualstudio.com/content/problem/129600/gradle-build-failing-on-vs2017-hosted-agent-due-to.html

**Comment by madhurig** [comment]
@AlasdairSQR: It looks like you are using the "Hosted" queue. Please switch to the "Hosted VS2017" queue. The "Hosted" queue is for legacy builds and not being updated.  

Thanks,
Madhuri

**Comment by AlasdairSQR** [comment]
Thanks very much - I hadn't noticed that.  It also affects the Linux preview image - it would be great if you could update that image too.

**Comment by madhurig** [comment]
@AlasdairSQR: Are you able to use the "Hosted VS 2017" image without errors? The "Linux image" does not have the Android SDK installed.

**Comment by AlasdairSQR** [comment]
Yes, the 2017 agent works fine.  I'll mark this as closed.  It would be great to have as much feature/SDK support parity between the 2 images as possible (but I guess that's what you'd aim for).  Thanks!

**Comment by mkruczkowski** [comment]
This error still occurs even on "Hosted VS 2017".

```
You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27, Android SDK Build-Tools 27.0.3].
```

**Comment by madhurig** [comment]
@mkruczkowski: Please open a new issue and provide details on which SDK version you are targeting in your project.

**Comment by madhurig** [comment]
@mkruczkowski : I see you have opened issue https://github.com/Microsoft/vsts-image-generation/issues/150, we are investigating.
