### ISSUE TITLE
Publish images to Azure image gallery

### ISSUE THREAD

**Issue by dolly22** [Microsoft/vsts-image-generation#64]
Would is please be possible for you to publish released images to Azure image gallery? It would be a lot easier (and faster) to use base image from gallery to create customized vsts build agents on azure.

**Comment by chrisrpatterson** [comment]
We are currently not planning to do that as there is a lot of software installed here that we do not have rights to redistribute.

**Comment by spelltwister** [comment]
can you elaborate further on this?  what is not allowed to redistro and why does using packer get around that?

**Comment by spelltwister** [comment]
when i ran the packer script, it created some VM , keyvault and a bunch of things I was not expecting.  i had no credentials to log into that VM (that I'm aware of).  i wanted to just create the build server _image_ and had an unexpected (and large) VM created without knowing it.  I was going to just publish the image somewhere public so people don't have to to thru this for no reason, but if there are distro concerns....

**Comment by bryanmacfarlane** [comment]
@chrisrpatterson to elaborate.  regarding creating the VM we should ensure the contribution guide and instructions make it clear what it will do.  that's what packer does - create an image by using various VM providers - ours is azure.

**Comment by spelltwister** [comment]
it created more than an image though.  it created a full, running VM whose credentials i am unaware of along with other resources.  i was expecting to see just images at the end.

**Comment by spelltwister** [comment]
further, what about packer gets around distro concerns and what pieces have that concern.  i would just upload this to gallery myself, but if there are issues, i'd rather address them first.

**Comment by chrisrpatterson** [comment]
@spelltwister what gets around the distribution is you are the one running the automated process that is downloading files from Oracle, Google, etc.  It is not me running them and then uploading a VM for you to download.
