### ISSUE TITLE
Add Selenium Drivers to Hosted Agents

### ISSUE THREAD

**Issue by danjcarpenter** [Microsoft/vsts-image-generation#66]
Would it be possible to install drivers for Selenium onto the Hosted Agents? e.g. [WebDriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/), IEDriver GeckoDriver, etc?

If not, what would be the best approach for running Selenium tests on a Hosted Agent as a part of a CI pipeline?

**Comment by bryanmacfarlane** [comment]
The work for this is in progress.  Hopefully in the next image update.

**Comment by lokesh755** [comment]
Selenium drivers are added to Hosted Agents in latest release

**Comment by markhobson** [comment]
Are there any plans to add these Selenium drivers to the Ubuntu 16.04 agent too?

**Comment by dakale** [comment]
@markhobson Please open a new issue so I can route it accordingly. This is something we could support

**Comment by mahilleb-msft** [comment]
Is there a plan to add an Edge webdriver? https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ ?
