### ISSUE TITLE
Add PIP VS images

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/vsts-image-generation#68]

**Comment by jonbgallant** [comment]
This would be really helpful....please also add for Linux Agents.

**Comment by lokesh755** [comment]
Pip is installed on both VS2015 and VS2017 images. Just that it's path is not added to Machine path in VS2017 image. I will add it in next release. In mean time pip can be used by adding it's path to Machine Path as shown below.

`$env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts"`

**Comment by jonbgallant** [comment]
@lokesh755 - Can you add to the Linux agents as well?  That's my primary use case ATM.

**Comment by bryanmacfarlane** [comment]
@jonbgallant - can you create a separate issue?  I'll take care of it.

**Comment by jonbgallant** [comment]
Thanks @bryanmacfarlane - https://github.com/Microsoft/vsts-image-generation/issues/72
