### ISSUE TITLE
C++ Build: Platform Toolset v141 Missing

### ISSUE THREAD

**Issue by stephenegriffin** [Microsoft/vsts-image-generation#76]
Hosted 2017 ought to support the v141 toolset, but it appears only v140 is installed:
##[warning]Visual Studio version '15.0' not found. Falling back to version '14.0'.
##[error]C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): Error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

Can we get v141 installed on Hosted 2017?

**Comment by bryanmacfarlane** [comment]
The hosted image is updated on a monthly basis pulling the latest VS.   So when VS updates to 141, the next monthly image will carry it.

**Comment by stephenegriffin** [comment]
This was working in my CI release on 2-1, the last time I checked in to my project. I queued a CI build today and it fails with this error. Clearly the hosted 2017 image DID have v141 and now it does not. Do we know which checkin broke this and which one will be fixing it?

**Comment by bryanmacfarlane** [comment]
@stephenegriffin - thanks.  As a guess, I would say VS updates ran in one case and in the other it didn't.  But that's just a guess.  We will investigate.  VS Updates shouldn't run once the image is provisioned into the pool.  Nothing changed in the install script so this is something dynamic: https://github.com/Microsoft/vsts-image-generation/commits/master/images/win/scripts/Installers/Vs2017/Install-VS2017.ps1

**Comment by stephenegriffin** [comment]
So - I was digging a bit more on this. I found the Agent Queues which shows me which pools my builds are queuing in. Despite having the default queue of Hosted VS2017 selected on my build definitions, it looks like all of my builds are queuing in Hosted instead. That explains the lack of capabilities. But something is definitely wrong with how my agents are being selected. There's still a bug here, but now I don't know where it is.

**Comment by stephenegriffin** [comment]
I have filed this: https://developercommunity.visualstudio.com/content/problem/200822/hosted-vs2017-builds-queuing-in-hosted-agents.html

**Comment by lokesh755** [comment]
Closing this issue since it's unrelated image-generation process.

**Comment by DudnykOleksandr** [comment]
I appeared to me, that the reason for the problem was a not needed VCTargetsPath system variable. After removing it, VS 2017 now sees V141 toolset.
I had VS 2017 Community first, maybe that made the problem.

**Comment by maharvey** [comment]
@DudnykOleksandr  Thank you! I've been trying to solve this for VS2017 for a week. After reading your comment I found that VCTargetsPath was set in the System Environment Variables. Removing it fixed the problem.
