### ISSUE TITLE
Add SonarQube Scanner

### ISSUE THREAD

**Issue by viperx77** [Microsoft/vsts-image-generation#77]
I would like the SonarQube.Scanner.MSBuild.exe (and dependencies) as default part of the VS 2017 Hosted Build Agent

**Comment by chrisrpatterson** [comment]
I think those can easily be pulled at runtime as part of your build.

**Comment by viperx77** [comment]
Sure, anything could be pulled at runtime.  What's the criteria for what should be added to the agent?

**Comment by bryanmacfarlane** [comment]
Some stuff is much harder at runtime.  Very large, msi's, requires reboots etc...  It's a question of size, how easy to pull and how common is it.  We have a finite amount of space on the image.  **Sonar is pretty common**.  If it's common and small then we should consider.  But the other question is maintenance - we need to add tests, validation and support on every image generation.  Which is of course possible but goes back to how common.

If it's trivial to pull, you can create an extension as a tool installer task (we have a category for that).  Actually, it would be best if the SonarQube extension added that task.  But that's an extra step for the consumer.

Judgement call for @chrisrpatterson

**Comment by Davilink** [comment]
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube

**Comment by chrisrpatterson** [comment]
The documentation seems to indicate that the extension already takes care of acquiring the scanner for msbuild https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Extension+for+VSTS-TFS
