### ISSUE TITLE
Error Installing Google Chrome

### ISSUE THREAD

**Issue by lokesh755** [Microsoft/vsts-image-generation#80]
It seems choco install is failing for Google Chrome with below error. 

`Error - hashes do not match. Actual value was 'DFE3E67EDD44FDC66E49B18AEF9204F8BB7A36093B075B5A7668CD7B283BDCE7'.
ERROR: Checksum for 'C:\Users\Administrator\AppData\Local\Temp\chocolatey\GoogleChrome\64.0.3282.16800\googlechromestandaloneenterprise64.msi' did not meet '1b19f94f510b70e779253169a02c9f3d5b092b8dafd19a37780b05964450f808' for checksum type 'sha256'. Conside
r passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of googlechrome was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.`

**Comment by maysamms** [comment]
Hi, can you help me with chrome installation, @lokesh755 , please?
[](https://github.com/Microsoft/vsts-image-generation/issues/193)
