### ISSUE TITLE
Request: Add 'Yarn' to image

### ISSUE THREAD

**Issue by ctolkien** [Microsoft/vsts-image-generation#84]
Restoring from NPM consumes a large amount of build time and is often flaky (npm, being what it is).

**Comment by bryanmacfarlane** [comment]
Sounds like a reasonable request.  Would you need many SxS or is latest enough?  Is latest stable enough?  Finally, is the download small and easy to acquire (we could also make a tool installer task like the node one).

**Comment by ctolkien** [comment]
Latest stable channel I would suggest. Download is 1.3mb

https://yarnpkg.com/en/docs/install

It is available on `chocolatey` (which I note you use for other services on Windows), or there is a MSI

I'm not sure of the base Linux image you use, but it's compatible with all the major package repositories. Full docs in the above link.

**Comment by densto88** [comment]
There's actually already a really good Yarn Installer in the marketplace that you can use (I have used it in several build definitions and it has worked great.)
https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-yarn

**Comment by ctolkien** [comment]
I think a lot of the pain points with `npm` are going to be resolved with [npm ci](https://docs.npmjs.com/cli/ci).


Am happy to close this out if there is an established task which handles yarn.
