### ISSUE TITLE
Validation for Wix and SSDT fails with the VS2017 image script

### ISSUE THREAD

**Issue by NateB2** [Microsoft/vsts-image-generation#88]
Upon running the Packer build script for VS 2017, validation fails for SSDT and Wix.  Upon examination, it appears as if the package array has been moved from "state.json" to "state.packages.json".  When I changed the references to the new file, the validation passed.  I submitted a PR for it here: https://github.com/Microsoft/vsts-image-generation/pull/87

**Comment by lokesh755** [comment]
Thanks for sending the PR. Will test and merge.

**Comment by lokesh755** [comment]
Merged PR
