### ISSUE TITLE
Request: Upgrade VS2017 to v15.6

### ISSUE THREAD

**Issue by SvenLauterbach** [Microsoft/vsts-image-generation#94]
A few days ago, Visual Studio v15.6 was released. It would be great to know, when the "Hosted VS2017" VSTS Agent will receive this update.

**Comment by lokesh755** [comment]
Hosted VS2017 will be updated this week

**Comment by lokesh755** [comment]
Hosted VS2017 pool is now updated with latest VS 15.6

**Comment by SvenLauterbach** [comment]
And the packaging of wsp files is working again! Great, thank you @lokesh755
